pushed 1.0.0

diff --git a/tests/docker/ducker-ak b/tests/docker/ducker-ak
--- a/tests/docker/ducker-ak
+++ b/tests/docker/ducker-ak
@@ -31,30 +31,18 @@ ducker_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 # The absolute path to the root Kafka directory
 kafka_dir="$( cd "${ducker_dir}/../.." && pwd )"
 
-# The absolute path to the directory to hold the necessary files to construct a ducker image for executing Kafka in native mode.
-tmp_native_dir=${ducker_dir}/native
-
 # The memory consumption to allow during the docker build.
 # This does not include swap.
 docker_build_memory_limit="3200m"
 
-# The maximum memory consumption to allow in containers.
+# The maximum mmemory consumption to allow in containers.
 docker_run_memory_limit="2000m"
 
 # The default number of cluster nodes to bring up if a number is not specified.
 default_num_nodes=14
 
-# The default OpenJDK base image.
-default_jdk="openjdk:17-buster"
-
 # The default ducker-ak image name.
 default_image_name="ducker-ak"
-
-# The default kafka server mode.
-default_kafka_mode="jvm"
-
-# Port to listen on when debugging
-debugpy_port=5678
 
 # Display a usage message on the terminal and exit.
 #
@@ -70,7 +58,7 @@ help|-h|--help
     Display this help message
 
 up [-n|--num-nodes NUM_NODES] [-f|--force] [docker-image]
-        [-C|--custom-ducktape DIR] [-e|--expose-ports ports]
+        [-C|--custom-ducktape DIR]
     Bring up a cluster with the specified amount of nodes (defaults to ${default_num_nodes}).
     The docker image name defaults to ${default_image_name}.  If --force is specified, we will
     attempt to bring up an image even some parameters are not valid.
@@ -79,24 +67,10 @@ up [-n|--num-nodes NUM_NODES] [-f|--force] [docker-image]
     ducktape source code directory before bringing up the nodes.  The provided
     directory should be the ducktape git repo, not the ducktape installed module directory.
 
-    if --expose-ports is specified then we will expose those ports to random ephemeral ports
-    on the host. The argument can be a single port (like 5005), a port range like (5005-5009)
-    or a combination of port/port-range separated by comma (like 2181,9092 or 2181,5005-5008).
-    By default no port is exposed. See README.md for more detail on this option.
-    
-    Note that port 5678 will be automatically exposed for ducker01 node and will be mapped to 5678 
-    on your local machine to enable debugging in VS Code.
-
-test [-d|--debug] [test-name(s)] [-- [ducktape args]]
+test [test-name(s)]
     Run a test or set of tests inside the currently active Ducker nodes.
-    For example, to run the system test produce_bench_test, you would run:
-        ./tests/docker/ducker-ak test ./tests/kafkatest/tests/core/produce_bench_test.py
-    
-    If --debug is passed, the tests will wait for remote VS Code debugger to connect on port 5678:
-        ./tests/docker/ducker-ak test --debug ./tests/kafkatest/tests/core/produce_bench_test.py
-    
-    To pass arguments to underlying ducktape invocation, pass them after `--`, e.g.:
-        ./tests/docker/ducker-ak test ./tests/kafkatest/tests/core/produce_bench_test.py -- --test-runner-timeout 1800000
+    For example, to run the Muckrake test simple_consumer_shell_test, you would run:
+        ./tests/docker/ducker-ak test ./tests/kafkatest/test/core/simple_consumer_shell_test.py
 
 ssh [node-name|user-name@node-name] [command]
     Log in to a running ducker container.  If node-name is not given, it prints
@@ -106,10 +80,9 @@ ssh [node-name|user-name@node-name] [command]
     is specified, we will run that command.  Otherwise, we will provide a login
     shell.
 
-down [-q|--quiet] [-f|--force]
+down [-q|--quiet]
     Tear down all the currently active ducker-ak nodes.  If --quiet is specified,
-    only error messages are printed. If --force or -f is specified, "docker rm -f"
-    will be used to remove the nodes, which kills currently running ducker-ak test.
+    only error messages are printed.
 
 purge [--f|--force]
     Purge Docker images created by ducker-ak.  This will free disk space.
@@ -191,12 +164,6 @@ must_popd() {
     popd &> /dev/null || die "failed to popd"
 }
 
-echo_and_do() {
-    local cmd="${@}"
-    echo "${cmd}"
-    ${cmd}
-}
-
 # Run a command and die if it fails.
 #
 # Optional flags:
@@ -247,52 +214,29 @@ ducker_build() {
     SECONDS=0
 
     must_pushd "${ducker_dir}"
-    # Tip: if you are scratching your head for some dependency problems that are referring to an old code version
-    # (for example java.lang.NoClassDefFoundError), add --no-cache flag to the build shall give you a clean start.
-    echo_and_do docker build --memory="${docker_build_memory_limit}" \
-        --build-arg "ducker_creator=${user_name}" \
-        --build-arg "jdk_version=${jdk_version}" \
-        --build-arg "UID=${UID}" \
-        --build-arg "KAFKA_MODE=${kafka_mode}" \
-        -t "${image_name}" \
+    must_do -v -o docker build --memory="${docker_build_memory_limit}" \
+        --build-arg "ducker_creator=${user_name}" -t "${image_name}" \
         -f "${ducker_dir}/Dockerfile" ${docker_args} -- .
     docker_status=$?
     must_popd
     duration="${SECONDS}"
     if [[ ${docker_status} -ne 0 ]]; then
-        echo "ERROR: Failed to build ${what} image after $((${duration} / 60))m \
-$((${duration} % 60))s."
-        echo "If this error is unexpected, consider running 'docker system prune -a' \
-to clear old images from your local cache."
-        cleanup_native_dir
-        exit 1
+        die "** ERROR: Failed to build ${what} image after $((${duration} / 60))m \
+$((${duration} % 60))s.  See ${build_log} for details."
     fi
-    echo "Successfully built ${what} image in $((${duration} / 60))m \
+    echo "** Successfully built ${what} image in $((${duration} / 60))m \
 $((${duration} % 60))s.  See ${build_log} for details."
 }
 
 docker_run() {
     local node=${1}
     local image_name=${2}
-    local ports_option=${3}
-    local port_mapping=${4}
-
-    local expose_ports=""
-    if [[ -n ${ports_option} ]]; then
-        expose_ports="-P"
-        for expose_port in ${ports_option//,/ }; do
-            expose_ports="${expose_ports} --expose ${expose_port}"
-        done
-    fi
-    if [[ -n ${port_mapping} ]]; then
-        expose_ports="${expose_ports} -p ${port_mapping}:${port_mapping}"
-    fi
 
     # Invoke docker-run. We need privileged mode to be able to run iptables
     # and mount FUSE filesystems inside the container.  We also need it to
     # run iptables inside the container.
     must_do -v docker run --privileged \
-        -d -t -h "${node}" --network ducknet "${expose_ports}" \
+        -d -t --net=host -h "${node}" --network ducknet \
         --memory=${docker_run_memory_limit} --memory-swappiness=1 \
         -v "${kafka_dir}:/opt/kafka-dev" --name "${node}" -- "${image_name}"
 }
@@ -306,37 +250,11 @@ setup_custom_ducktape() {
     docker_run ducker01 "${image_name}"
     local running_container="$(docker ps -f=network=ducknet -q)"
     must_do -v -o docker cp "${custom_ducktape}" "${running_container}:/opt/ducktape"
-    docker exec --user=root ducker01 bash -c 'set -x && cd /opt/kafka-dev/tests && sudo python3 ./setup.py develop install && cd /opt/ducktape && sudo python3 ./setup.py develop install'
+    docker exec --user=root ducker01 bash -c 'set -x && cd /opt/kafka-dev/tests && sudo python ./setup.py develop install && cd /opt/ducktape && sudo python ./setup.py develop install'
     [[ $? -ne 0 ]] && die "failed to install the new ducktape."
     must_do -v -o docker commit ducker01 "${image_name}"
     must_do -v docker kill "${running_container}"
     must_do -v docker rm ducker01
-}
-
-cleanup_native_dir() {
-    if [ -d "${tmp_native_dir}" ]; then
-        echo "Deleting temporary native dir: ${tmp_native_dir}"
-        rm -rf "${tmp_native_dir}"
-    fi
-}
-
-prepare_native_dir() {
-    echo "Mode provided for system tests run: $kafka_mode"
-    must_pushd "${kafka_dir}"
-    cleanup_native_dir && mkdir "${tmp_native_dir}"
-
-    if [ "$kafka_mode" == "native" ]; then
-        kafka_tarball_filename=(core/build/distributions/kafka*SNAPSHOT.tgz)
-        if [ ! -e "${kafka_tarball_filename[0]}" ]; then
-            echo "Kafka tarball not present. Building Kafka tarball for native image."
-            ./gradlew clean releaseTarGz
-        fi
-
-        cp core/build/distributions/kafka*SNAPSHOT.tgz "${tmp_native_dir}"/kafka.tgz
-        cp -r docker/native/native-image-configs "${tmp_native_dir}"
-        cp docker/native/native_command.sh "${tmp_native_dir}"
-    fi
-    must_popd
 }
 
 ducker_up() {
@@ -346,16 +264,11 @@ ducker_up() {
             -C|--custom-ducktape) set_once custom_ducktape "${2}" "the custom ducktape directory"; shift 2;;
             -f|--force) force=1; shift;;
             -n|--num-nodes) set_once num_nodes "${2}" "number of nodes"; shift 2;;
-            -j|--jdk) set_once jdk_version "${2}" "the OpenJDK base image"; shift 2;;
-            -e|--expose-ports) set_once expose_ports "${2}" "the ports to expose"; shift 2;;
-            -m|--kafka_mode) set_once kafka_mode "${2}" "the mode in which kafka will run"; shift 2;;
             *) set_once image_name "${1}" "docker image name"; shift;;
         esac
     done
     [[ -n "${num_nodes}" ]] || num_nodes="${default_num_nodes}"
-    [[ -n "${jdk_version}" ]] || jdk_version="${default_jdk}"
-    [[ -n "${kafka_mode}" ]] || kafka_mode="${default_kafka_mode}"
-    [[ -n "${image_name}" ]] || image_name="${default_image_name}-${jdk_version/:/-}"
+    [[ -n "${image_name}" ]] || image_name=ducker-ak
     [[ "${num_nodes}" =~ ^-?[0-9]+$ ]] || \
         die "ducker_up: the number of nodes must be an integer."
     [[ "${num_nodes}" -gt 0 ]] || die "ducker_up: the number of nodes must be greater than 0."
@@ -370,9 +283,7 @@ use only ${num_nodes}."
 
     docker ps >/dev/null || die "ducker_up: failed to run docker.  Please check that the daemon is started."
 
-    prepare_native_dir
     ducker_build "${image_name}"
-    cleanup_native_dir
 
     docker inspect --format='{{.Config.Labels}}' --type=image "${image_name}" | grep -q 'ducker.type'
     local docker_status=${PIPESTATUS[0]}
@@ -403,10 +314,9 @@ attempting to start new ones."
     if [[ -n "${custom_ducktape}" ]]; then
         setup_custom_ducktape "${custom_ducktape}" "${image_name}"
     fi
-    docker_run ducker01 "${image_name}" "${expose_ports}" "${debugpy_port}"
-    for n in $(seq -f %02g 2 ${num_nodes}); do
+    for n in $(seq -f %02g 1 ${num_nodes}); do
         local node="ducker${n}"
-        docker_run "${node}" "${image_name}" "${expose_ports}"
+        docker_run "${node}" "${image_name}"
     done
     mkdir -p "${ducker_dir}/build"
     exec 3<> "${ducker_dir}/build/node_hosts"
@@ -422,10 +332,6 @@ attempting to start new ones."
             bash -c "grep -v ${node} /opt/kafka-dev/tests/docker/build/node_hosts >> /etc/hosts"
         [[ $? -ne 0 ]] && die "failed to append to the /etc/hosts file on ${node}"
     done
-
-    if [ "$kafka_mode" == "native" ]; then
-      docker exec --user=root ducker01 bash -c 'cp /opt/kafka-binary/kafka.Kafka /opt/kafka-dev/kafka.Kafka'
-    fi
 
     echo "ducker_up: added the latest entries to /etc/hosts on each node."
     generate_cluster_json_file "${num_nodes}" "${ducker_dir}/build/cluster.json"
@@ -489,62 +395,30 @@ EOF
     exec 3>&-
 }
 
-correct_latest_link() {
-    local result_dir="${kafka_dir}/results"
-    local latest_link="${result_dir}/latest"
-
-    # Correct the link if it's a symbolic link and broken.
-    if [[ -L "${latest_link}" ]] && [[ ! -e "${latest_link}" ]]; then
-        local latest_test_dirname=$(basename "$(readlink "${latest_link}")")
-        unlink "${latest_link}"
-        ln -s "${result_dir}/${latest_test_dirname}" "${latest_link}"
-    fi
-}
-
 ducker_test() {
     require_commands docker
     docker inspect ducker01 &>/dev/null || \
         die "ducker_test: the ducker01 instance appears to be down. Did you run 'ducker up'?"
-    declare -a test_name_args=()
-    local debug=0
-    while [[ $# -ge 1 ]]; do
-        case "${1}" in
-            -d|--debug) debug=1; shift;;
-            --) shift; break;;
-            *) test_name_args+=("${1}"); shift;;
-        esac
-    done
-    local ducktape_args=${*}
-    
-    [[ ${#test_name_args} -lt 1 ]] && \
+    [[ $# -lt 1 ]] && \
         die "ducker_test: you must supply at least one system test to run. Type --help for help."
-    local test_names=""
-
-    for test_name in ${test_name_args[*]}; do
+    local args=""
+    local kafka_test=0
+    for arg in "${@}"; do
         local regex=".*\/kafkatest\/(.*)"
-        if [[ $test_name =~ $regex ]]; then
+        if [[ $arg =~ $regex ]]; then
             local kpath=${BASH_REMATCH[1]}
-            test_names="${test_names} ./tests/kafkatest/${kpath}"
+            args="${args} ./tests/kafkatest/${kpath}"
         else
-            test_names="${test_names} ${test_name}"
+            args="${args} ${arg}"
         fi
     done
-    
     must_pushd "${kafka_dir}"
-    ( (test -f ./gradlew || gradle) && ./gradlew systemTestLibs ) || die "ducker_test: Failed to build system test libraries, please check the error log."
+    ls ./core/build/distributions/kafka_*.tgz &> /dev/null
+    [[ $? -eq 0 ]] || die "Failed to find core/build/distributions/kafka_*.tgz.  Did you run ./gradlew releaseTarGz?"
     must_popd
-    if [[ "${debug}" -eq 1 ]]; then
-        local ducktape_cmd="python3 -m debugpy --listen 0.0.0.0:${debugpy_port} --wait-for-client /usr/local/bin/ducktape"
-    else
-        local ducktape_cmd="ducktape"
-    fi
-
-    cmd="cd /opt/kafka-dev && ${ducktape_cmd} --cluster-file /opt/kafka-dev/tests/docker/build/cluster.json $test_names $ducktape_args"
-    echo "docker exec ducker01 bash -c \"${cmd}\""
-    docker exec --user=ducker ducker01 bash -c "${cmd}"
-    docker_status=$?
-    correct_latest_link
-    exit "${docker_status}"
+    cmd="cd /opt/kafka-dev && ducktape --cluster-file /opt/kafka-dev/tests/docker/build/cluster.json $args"
+    echo "docker exec -it ducker01 bash -c \"${cmd}\""
+    exec docker exec --user=ducker -it ducker01 bash -c "${cmd}"
 }
 
 ducker_ssh() {
@@ -598,11 +472,9 @@ echo_running_container_names() {
 ducker_down() {
     require_commands docker
     local verbose=1
-    local force_str=""
     while [[ $# -ge 1 ]]; do
         case "${1}" in
             -q|--quiet) verbose=0; shift;;
-            -f|--force) force_str="-f"; shift;;
             *) die "ducker_down: unexpected command-line argument ${1}";;
         esac
     done
@@ -623,7 +495,7 @@ ducker_down() {
     if [[ -n "${running_containers}" ]]; then
         must_do ${verbose_flag} docker kill "${running_containers}"
     fi
-    must_do ${verbose_flag} docker rm ${force_str} "${all_containers}"
+    must_do ${verbose_flag} docker rm "${all_containers}"
     must_do ${verbose_flag} -o rm -f -- "${ducker_dir}/build/node_hosts" "${ducker_dir}/build/cluster.json"
     if docker network inspect ducknet &>/dev/null; then
         must_do -v docker network rm ducknet
